language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
script:
  - sbt clean coverage test
after_success:
  - sbt codacyCoverage
deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt publish
  on:
    tags: true
env:
  global:
  - secure: TCFeIck1jJ0ZN4z2jw1v3Ie5EXPiBbRH+Wg85Uhq2nYTHYMvoWwBekCu7Qn/xtPdqpY1/ZkGUisZuzvPGdpMB+XZGBlLYd612dBeQv3Gt8yd7ME09sDsPPogjciQ7pauFza/spKVXnnF1NopeRVkEIq6f6pbkOtCWVg07kJduhGQjI9TqH45Igl2ySrRvca5FtgPqVf606o/BJTql8SDLyP//CJmtF0J1aJbkH1zZSFm1hf4mtYN7wCS+EEpP49+G3mYHDdPzEcn6LDScl35/SdnbTrS+BUvbDT2AQ2ZSahH+itaAgjdgq+Sdp0n5+tUQbkndF+4ZpRvWPFU6EkaWVZSEglIeqEIsA1HUimAbmzrxv2hfcYTN5KflmkyV9BQeeittCpr2V3h4Lvc/fKNyEX1r6oP1YDdaaiuDUgNpEg1CtX9i32PselSypZWVM+ZEwrYUwwEnpVRDke2gCHkWX9Fwo1kz2GakFfUeKxOuGjgOnm0YYQ8kIxXXhKk/MdJHGN+tUxJcJin2iZP5QcRMJSsrp2tQbeQJfCO4ENU5fCZsLEOz1m340GO71Zwgabnl7JZfPb+9xNWh7nhsHRXM2CV8i8SJdO/ClENlZpSWqtLYClgpLKwYhLRAMaOM1qPMwNFZN0hn3XbDUG2ZeUOk5lLDBLTcViseZ6yvC5Avn0=
  - secure: NB0ea+7UFcxJzUSA5jzn/+Iuu4PybpGrXoyBaAVnA2djr/8byfAkAb5yzbLFHdVFPsNscjvmqvKx0kxD9Om0dsAtUH+VGQz+UOJgBWqse0r7fTl3gwQWtzf1wo96MJOdaGNFWz+jWy8tP/EeAFaVCun02JbUyjwyXjW4FI5iz1q0Z+wW1JpCN4v+Zqt+4uvHFswe/wgo9SGdTrL5Mjj8r4i6Nt/6c0alTlYL11N/caSV5is1izzy6INq6WBgvDtVzEo3qjFb7TLzKvF62CMmsw+z9X5tTunbXD4kNxqSrAsmiQaCbNldzGlJYqtNnfXygpC7RfWk3lzLa4Q/rfkqZRkGLcvbjmvaD3iPSkpJEGNH+oAzK04S2Ctx/dMUyASmjeMpJn+2/m7pAiIWJc0C0pnZM8MjNWHcB+knBJ3m+wxKLhbKfoHb1lVtbQ0f3lUrMlDzEES1G+9qHQdOSjvoOXE5RRqV19sffB1TVa+3ncJQMfcUUKg9CaZ5V5mcV8UMgC8MHXwTCqXsSTR5Bn1jEkTiz1uHCUw9UCaHMYHyKyeulX5n5Feqq0iZjQzZp/Hell3QWYBlNGhAqbcnQqTtm/kJbqrwhAAN3WnjeS2YWtMJtCnAVAbCNE6SE8QVfwOR3K7/NDVsu/HBpNbSEtC2BHYAvMCqqCMa8OclOX29GJk=
  - secure: CcO1B6twPv8GtY4F139t11cTDhM1bsgsjt0NptoT9PK7As93YUx6LGZ95wSyY2k/xnlDExmEkhFqBMQw451y3/FgabtDvTfbBdy//Kh7cOchFH0OWWj+zTkY/z9ETo1x42xsFXBrTPH+QLNQhv4sw0berfMbq/2aUKuiyGRWCW0HWoeWRgOcaBFk0Rj4oICjPvS32lJLVkWizAUqieaOwrZ0vHkqVsxdQSBu73kKdJiCTvNMiDeE6bSJJzpMoIbYIOtbG176YJnJocu40uQxQyXTRnKxw6OWCbBFUzSThfKCpIgni1/IiSr5NHrq8RDKmYZgZozUkpCkUQcnoinEyhWR5Tqhc1AC1cQBpmhmEm4vfFIG1NUg4guT80f0wdg3xb98dWReuNPAzkTBL/FLyMV47QOi5ajwOuYNxWdT+ajvyrg2zii/ggLDxhNhHpY1FKu8lM2Bvz2lQKB8O5oiETVKoeHRlvxfV+UFiu/e4KYUq/6U+NU+eT4e2B+KGeYs3xwxraIp2VUrYDNQOLrBbC0D/vJyUzhCY8UjVLxsPMB35WXb1gHtltGBs8LDDpEtdtq40C0+wLNoi8fqP/qTZYwy8ZDWTbF2L8lH9AKXiuhpmREDP9jqqlEFLbyTKAzwuA0UXRSOYJxveotfitt00JxVjehdbjCK+gkE7PDib9k=
